In [215]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from imblearn.over_sampling import SMOTE

In [216]:
from sklearn import metrics
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score

In [217]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [218]:
from imblearn.over_sampling import RandomOverSampler

In [219]:
global scaler

In [220]:
data = pd.read_csv('https://github.com/AnonymousCITK/ProjectML/raw/main/heart_disease.csv')
# print(data.shape)
# data.head(100)
data.tail(100)


Gender  age  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
4138       1   67              1        25.0     0.0                0   
4139       0   53              0         0.0     NaN                0   
4140       1   49              1        10.0     0.0                0   
4141       1   48              0         0.0     0.0                0   
4142       1   47              1        20.0     0.0                0   
...      ...  ...            ...         ...     ...              ...   
4233       1   50              1         1.0     0.0                0   
4234       1   51              1        43.0     0.0                0   
4235       0   48              1        20.0     NaN                0   
4236       0   44              1        15.0     0.0                0   
4237       0   52              0         0.0     0.0                0   

      prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  \
4138             1         0    221.0  144.0   84.0  24.92       72.0   
4139             0         0    252.0  122.5   75.5  25.29       75.0   
4140             0         0    305.0  135.0   82.0  26.29       84.0   
4141             0         0    206.0  118.0   81.0  28.13       72.0   
4142             1         0    234.0  162.0  110.0  27.51       80.0   
...            ...       ...      ...    ...    ...    ...        ...   
4233             1         0    313.0  179.0   92.0  25.97       66.0   
4234             0         0    207.0  126.5   80.0  19.71       65.0   
4235             0         0    248.0  131.0   72.0  22.00       84.0   
4236             0         0    210.0  126.5   87.0  19.16       86.0   
4237             0         0    269.0  133.5   83.0  21.47       80.0   

      glucose  Target  
4138     73.0       0  
4139     71.0       0  
4140     65.0       0  
4141     87.0       0  
4142     85.0       0  
...       ...     ...  
4233     86.0       1  
4234     68.0       0  
4235     86.0       0  
4236      NaN       0  
4237    107.0       0  

[100 rows x 15 columns]

In [221]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4238 entries, 0 to 4237
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Gender           4238 non-null   int64  
 1   age              4238 non-null   int64  
 2   currentSmoker    4238 non-null   int64  
 3   cigsPerDay       4209 non-null   float64
 4   BPMeds           4185 non-null   float64
 5   prevalentStroke  4238 non-null   int64  
 6   prevalentHyp     4238 non-null   int64  
 7   diabetes         4238 non-null   int64  
 8   totChol          4188 non-null   float64
 9   sysBP            4238 non-null   float64
 10  diaBP            4238 non-null   float64
 11  BMI              4219 non-null   float64
 12  heartRate        4237 non-null   float64
 13  glucose          3850 non-null   float64
 14  Target           4238 non-null   int64  
dtypes: float64(8), int64(7)
memory usage: 496.8 KB


In [222]:
data.columns

Index(['Gender', 'age', 'currentSmoker', 'cigsPerDay', 'BPMeds',
       'prevalentStroke', 'prevalentHyp', 'diabetes', 'totChol', 'sysBP',
       'diaBP', 'BMI', 'heartRate', 'glucose', 'Target'],
      dtype='object')

In [223]:
data.describe()

Gender          age  currentSmoker   cigsPerDay       BPMeds  \
count  4238.000000  4238.000000    4238.000000  4209.000000  4185.000000   
mean      0.429212    49.584946       0.494101     9.003089     0.029630   
std       0.495022     8.572160       0.500024    11.920094     0.169584   
min       0.000000    32.000000       0.000000     0.000000     0.000000   
25%       0.000000    42.000000       0.000000     0.000000     0.000000   
50%       0.000000    49.000000       0.000000     0.000000     0.000000   
75%       1.000000    56.000000       1.000000    20.000000     0.000000   
max       1.000000    70.000000       1.000000    70.000000     1.000000   

       prevalentStroke  prevalentHyp     diabetes      totChol        sysBP  \
count      4238.000000   4238.000000  4238.000000  4188.000000  4238.000000   
mean          0.005899      0.310524     0.025720   236.721585   132.352407   
std           0.076587      0.462763     0.158316    44.590334    22.038097   
min           0.000000      0.000000     0.000000   107.000000    83.500000   
25%           0.000000      0.000000     0.000000   206.000000   117.000000   
50%           0.000000      0.000000     0.000000   234.000000   128.000000   
75%           0.000000      1.000000     0.000000   263.000000   144.000000   
max           1.000000      1.000000     1.000000   696.000000   295.000000   

             diaBP          BMI    heartRate      glucose       Target  
count  4238.000000  4219.000000  4237.000000  3850.000000  4238.000000  
mean     82.893464    25.802008    75.878924    81.966753     0.151958  
std      11.910850     4.080111    12.026596    23.959998     0.359023  
min      48.000000    15.540000    44.000000    40.000000     0.000000  
25%      75.000000    23.070000    68.000000    71.000000     0.000000  
50%      82.000000    25.400000    75.000000    78.000000     0.000000  
75%      89.875000    28.040000    83.000000    87.000000     0.000000  
max     142.500000    56.800000   143.000000   394.000000     1.000000

In [224]:
data.isna().sum()

Gender               0
age                  0
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
Target               0
dtype: int64

In [225]:
data['Target'].value_counts()

0    3594
1     644
Name: Target, dtype: int64

In [226]:
data=data.dropna()
data.isna().sum()

Gender             0
age                0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
Target             0
dtype: int64

In [227]:
data.describe()

Gender          age  currentSmoker   cigsPerDay       BPMeds  \
count  3749.000000  3749.000000    3749.000000  3749.000000  3749.000000   
mean      0.445185    49.578821       0.488397     9.005335     0.030408   
std       0.497053     8.569322       0.499932    11.922440     0.171730   
min       0.000000    32.000000       0.000000     0.000000     0.000000   
25%       0.000000    42.000000       0.000000     0.000000     0.000000   
50%       0.000000    49.000000       0.000000     0.000000     0.000000   
75%       1.000000    56.000000       1.000000    20.000000     0.000000   
max       1.000000    70.000000       1.000000    70.000000     1.000000   

       prevalentStroke  prevalentHyp     diabetes      totChol        sysBP  \
count      3749.000000   3749.000000  3749.000000  3749.000000  3749.000000   
mean          0.005601      0.311816     0.027207   236.952787   132.365964   
std           0.074643      0.463297     0.162709    44.610417    22.051951   
min           0.000000      0.000000     0.000000   113.000000    83.500000   
25%           0.000000      0.000000     0.000000   206.000000   117.000000   
50%           0.000000      0.000000     0.000000   234.000000   128.000000   
75%           0.000000      1.000000     0.000000   264.000000   144.000000   
max           1.000000      1.000000     1.000000   696.000000   295.000000   

             diaBP          BMI    heartRate      glucose       Target  
count  3749.000000  3749.000000  3749.000000  3749.000000  3749.000000  
mean     82.933716    25.809651    75.703921    81.883169     0.152574  
std      11.933321     4.065894    11.957763    23.888039     0.359624  
min      48.000000    15.540000    44.000000    40.000000     0.000000  
25%      75.000000    23.090000    68.000000    71.000000     0.000000  
50%      82.000000    25.410000    75.000000    78.000000     0.000000  
75%      90.000000    28.060000    82.000000    87.000000     0.000000  
max     142.500000    56.800000   143.000000   394.000000     1.000000

In [228]:
data.columns
# data.describe()

Index(['Gender', 'age', 'currentSmoker', 'cigsPerDay', 'BPMeds',
       'prevalentStroke', 'prevalentHyp', 'diabetes', 'totChol', 'sysBP',
       'diaBP', 'BMI', 'heartRate', 'glucose', 'Target'],
      dtype='object')

In [229]:
train, valid, test = np.split(data.sample(frac=1),[int(0.6*len(data)), int(0.8*len(data))])
# y_train.value_counts().plot.pie(autopct = '%.2f')

In [230]:
def scale_dataset(dataframe, oversample=False):
  x = dataframe[dataframe.columns[:-1]].values
  y = dataframe[dataframe.columns[-1]].values
  scaler = MinMaxScaler()
  x = scaler.fit_transform(x)

  if oversample:
    ros = RandomOverSampler()
    x, y = ros.fit_resample(x,y)
  data = np.hstack((x, np.reshape(y, (-1, 1))))

  return data, x, y

In [231]:
train, x_train, y_train = scale_dataset(train, oversample=True)
valid, x_valid, y_valid = scale_dataset(valid, oversample=False)
test, x_test, y_test = scale_dataset(test, oversample=False)

In [232]:
print(len(y_train))
print(len(y_train == 1))
print(len(y_train == 0))

3800
3800
3800


In [233]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

#Logistic Regression

In [234]:
model = LogisticRegression()
model.fit(x_train, y_train)

LogisticRegression()

In [235]:
y_pred = model.predict(x_test)

In [236]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.59      0.72       639
           1       0.25      0.81      0.39       111

    accuracy                           0.62       750
   macro avg       0.60      0.70      0.56       750
weighted avg       0.84      0.62      0.67       750



In [237]:
confusion_matrix(y_test, y_pred)

array([[375, 264],
       [ 21,  90]])

In [238]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)
print("R-squared:", r2)

Mean Absolute Error: 0.38
Mean Squared Error: 0.38
Root Mean Squared Error: 0.6164414002968976
R-squared: -2.013576957238929


#SVM(Support Vector Machine)

In [239]:
svm_model = SVC()
svm_model.fit(x_train, y_train)

SVC()

In [240]:
svm_pred = svm_model.predict(x_test)

In [241]:
print(classification_report(y_test, svm_pred))

              precision    recall  f1-score   support

           0       0.91      0.66      0.76       639
           1       0.24      0.64      0.35       111

    accuracy                           0.65       750
   macro avg       0.58      0.65      0.56       750
weighted avg       0.81      0.65      0.70       750



In [242]:
confusion_matrix(y_test, svm_pred)

array([[419, 220],
       [ 40,  71]])

In [243]:
mae = mean_absolute_error(y_test, svm_pred)
mse = mean_squared_error(y_test, svm_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, svm_pred)

print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)
print("R-squared:", r2)

Mean Absolute Error: 0.3466666666666667
Mean Squared Error: 0.3466666666666667
Root Mean Squared Error: 0.5887840577551898
R-squared: -1.749228101340777


# Decision Tree

In [244]:
dt_model = DecisionTreeClassifier()
dt_model.fit(x_train, y_train)


DecisionTreeClassifier()

In [245]:
dt_pred=dt_model.predict(x_test)

In [246]:
print(classification_report(y_test, dt_pred))

              precision    recall  f1-score   support

           0       0.86      0.85      0.86       639
           1       0.19      0.21      0.20       111

    accuracy                           0.75       750
   macro avg       0.53      0.53      0.53       750
weighted avg       0.76      0.75      0.76       750



In [247]:
confusion_matrix(y_test, dt_pred)

array([[543,  96],
       [ 88,  23]])

In [248]:
mae = mean_absolute_error(y_test, dt_pred)
mse = mean_squared_error(y_test, dt_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, dt_pred)

print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)
print("R-squared:", r2)

Mean Absolute Error: 0.24533333333333332
Mean Squared Error: 0.24533333333333332
Root Mean Squared Error: 0.4953113498935123
R-squared: -0.9456075794103962


#KNN

In [249]:
knn_model = DecisionTreeClassifier()
knn_model.fit(x_train, y_train)


DecisionTreeClassifier()

In [250]:
knn_pred=knn_model.predict(x_test)

In [251]:
print(classification_report(y_test, knn_pred))

              precision    recall  f1-score   support

           0       0.86      0.84      0.85       639
           1       0.21      0.23      0.22       111

    accuracy                           0.75       750
   macro avg       0.54      0.54      0.54       750
weighted avg       0.77      0.75      0.76       750



In [252]:
confusion_matrix(y_test, knn_pred)

array([[539, 100],
       [ 85,  26]])

In [253]:
mae = mean_absolute_error(y_test, knn_pred)
mse = mean_squared_error(y_test, knn_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, knn_pred)

print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)
print("R-squared:", r2)

Mean Absolute Error: 0.24666666666666667
Mean Squared Error: 0.24666666666666667
Root Mean Squared Error: 0.496655480858378
R-squared: -0.9561815336463224


In [262]:
DATA = [0,68,0,0,0,0,0,0,242,146.5,71,25.21,100,96]
print(DATA)

[0, 68, 0, 0, 0, 0, 0, 0, 242, 146.5, 71, 25.21, 100, 96]


In [263]:
DATA_as_np_array = np.asarray(DATA)

#reshaping the array as prediction is only for 1 instance
DATA_reshape = DATA_as_np_array.reshape(1,-1)

# std_DATA = scaler.transform(DATA_reshape)
# print(std_DATA)

Lr_pred = model.predict(DATA_reshape)
print("L_R= ",Lr_pred)
Svm_pred = svm_model.predict(DATA_reshape)
print("SVM= ",Svm_pred)
Dt_pred = dt_model.predict(DATA_reshape)
print("DTC= ",Dt_pred)
Knn_pred = knn_model.predict(DATA_reshape)
print("KNN= ",Knn_pred)

# mn = int((Dt_pred + Knn_pred) / 2)
# mn = int((mn1 + mn2) / 2)
# print("Mean= ", mn)

# if (mn == 1):
#   print("The person have heart disease.\n")
# else:
#   print("The person does not have heart disease.\n")

L_R=  [1]
SVM=  [1]
DTC=  [0]
KNN=  [0]
